export const GET_SONGS = "GET_SONGS";
export const CREATE_SONG = "CREATE_SONG";
export const UPDATE_SONG_BY_ID = "UPDATE_SONG_BY_ID";
export const DELETE_SONG_BY_ID = "DELETE_SONG_BY_ID";


export const GET_TOTAL_NUMBER_OF_SONGS = "GET_TOTAL_NUMBER_OF_SONGS";
export const GET_TOTAL_NUMBER_OF_ARTISTS = "GET_TOTAL_NUMBER_OF_ARTISTS";
export const GET_TOTAL_NUMBER_OF_ALBUMS = "GET_TOTAL_NUMBER_OF_ALBUMS";
export const GET_TOTAL_NUMBER_OF_GENRE = "GET_TOTAL_NUMBER_OF_GENRE";
export const GET_TOTAL_NUMBER_OF_GENRE_IN_SONGS = "GET_TOTAL_NUMBER_OF_GENRE_IN_SONGS";
export const GET_TOTAL_NUMBER_OF_SONGS_IN_ALBUMS = "GET_TOTAL_NUMBER_OF_SONGS_IN_ALBUMS";
export const GET_ARTIST_STATS = "GET_ARTIST_STATS";
